# Generated by Django 5.1 on 2024-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(default='2024-08-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_unique_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_time',
            field=models.TimeField(),
        ),
    ]
