# Generated by Django 5.1 on 2024-08-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_transaction_type_alter_payment_bank_account'),
        ('trips', '0006_remove_trip_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mutual',
            new_name='brand_name',
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
