# Generated by Django 5.1 on 2024-08-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_mutual_payment_brand_name_calculate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_unique_number',
        ),
    ]
