# Generated by Django 4.2 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
