version: "3.8"

services:
  frontend:
    build: .
    image: frontend_image
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
