pipeline {
    agent any

    environment {
        FRONTEND_IMAGE = 'parenhark/frontend'
    }

    stages {
        stage('Clone Frontend Repo') {
            steps {
                git branch: 'develop-front', credentialsId: 'e92707da-8291-494e-bfdd-b2a93870460a', url: 'https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A204.git'
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('Frontend/front') {
                    script {
                        sh 'docker-compose build frontend'
                        sh 'docker tag frontend_image:latest $FRONTEND_IMAGE:$BUILD_NUMBER'
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'c23281eb-4db4-4090-973c-80cacc65904d', url: 'https://index.docker.io/v1/']) {
                        sh 'docker push $FRONTEND_IMAGE:$BUILD_NUMBER'
                    }
                }
            }
        }

        stage('Restart Frontend Only') {
            steps {
                dir('Frontend/front') {
                    script {
                        sh '''
                        docker-compose stop frontend &&
                        docker-compose up -d frontend
                        '''
                    }
                }
            }
        }

        stage('Connect Server') {
            steps {
                script {
                    sh 'docker network inspect app-network'
                    sh 'docker network connect app-network front-frontend-1'
                }
            }
        }
    }
}
