# Generated by Django 5.1 on 2024-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.CharField(default=1234, max_length=36),
            preserve_default=False,
        ),
    ]
