# Generated by Django 4.2 on 2024-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
