# Generated by Django 5.1 on 2024-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_user_alter_member_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_participate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bank_account',
            field=models.CharField(default='', max_length=30),
        ),
    ]
