# Generated by Django 5.1 on 2024-08-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_member_is_participate_alter_member_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
