# Generated by Django 5.1 on 2024-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_city_remove_trip_country_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default='여행 이름', max_length=30),
            preserve_default=False,
        ),
    ]
