# Generated by Django 5.1 on 2024-08-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='budget',
        ),
    ]
