# Generated by Django 5.1 on 2024-08-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_trip_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
