# Generated by Django 5.1 on 2024-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
